
# Etapa de construção
FROM node:18 AS build

WORKDIR /app

# Copia os arquivos de configuração do npm
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos da aplicação
COPY . .

# Cria a versão de produção da aplicação
RUN npm run build

# Etapa de execução
FROM node:18

WORKDIR /app

# Copia a pasta build da etapa de construção para a pasta atual
COPY --from=build /app/build /app/build

# Expõe a porta que será usada pelo servidor
EXPOSE 3000

# Comando para iniciar o servidor usando um servidor estático com Express
CMD ["npx", "serve", "-s", "build", "-l", "3000"]