services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: EGFUJN45U6WKSEFNSLKDGNSIT5W6
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/server-capixaba
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    networks:
      - web-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend-capixaba
    env_file:
      - .env
    restart: always
    environment:
      - HOST=0.0.0.0
    networks:
      - web-net
    depends_on:
      - backend

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - web-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    restart: always
    networks:
      - web-net

volumes:
  postgres_data: {}
networks:
  web-net:
    name: web-net
